model_name_or_path: Qwen/Qwen2.5-7B-Instruct
stage: sft
finetuning_type: lora
do_train: true
do_eval: true
do_predict: false
dataset: disc_law_llm_sft_train,disc_law_llm_sft_val
dataset_dir: ./dataset
template: qwen2
cutoff_len: 4096
max_samples: 500000
overwrite_cache: true
preprocessing_num_workers: 16
output_dir: ./outputs/qwen2.5-law-lora
logging_steps: 10
eval_strategy: steps
save_strategy: steps
save_steps: 200
eval_steps: 200
plot_loss: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
fp16: false
gradient_checkpointing: true
optim: paged_adamw_8bit
report_to: tensorboard
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
trust_remote_code: true
